### ISSUE TITLE
Unknown Licenses

### ISSUE THREAD

**Issue by Foggalong** [Foggalong/edinburgh-math-latex#1]
The following files have unknown licensing, and an effort should be made to find them:

- [x] `beamernotes.sty`
- [x] `beamerthemeUsherNew.sty`
- [ ] `edmaths.sty`
- [ ] `edmaths` documentation
- [x] University of Edinburgh logos
- [x] `setspace.sty`

**Comment by Foggalong** [comment]
@tkoeppe If you see this, let me know what license you released / would be happy to release edmaths :slightly_smiling_face:

**Comment by tkoeppe** [comment]
Hm, there wasn't any particular license initially, it was only meant for internal use. Let me think about ut.

**Comment by tkoeppe** [comment]
Oh, I mistook this for a different template -- never mind, edmaths.sty is welcome to have a permissive license, but I'm not entirely sure if I initiated it, or if it was based on some previous work. Let me reflect.

**Comment by Foggalong** [comment]
Closed in #9
