### ISSUE TITLE
Error in the documentation? (section 3.3 Fonts)

### ISSUE THREAD

**Issue by quark67** [Foggalong/edinburgh-math-latex#18]
**Describe the problem or request**
The documentation say that the package `fontenc` needs XeLaTeX or LuaLaTeX. This seems false (`fontspec` needs these engine, but here the `cmbright` option don't load `fontspec`, but `fontenc`).

**Screenshots**
<img width="790" alt="image" src="https://github.com/user-attachments/assets/da41f334-784e-4fa2-bc96-afc479b4901f">

**Additional context**
The lines 99 to 106 of `edmaths.sty` are:

```latex
% If with-cmbright selected, use the (sans-serif) Computer Modern Bright font.
\ifthenelse{\boolean{with-cmbright}}{
    % NOTE must be compiled with xelatex or luatex
    \RequirePackage{cmap}
    \RequirePackage{cmbright}
    \RequirePackage[T1]{fontenc}
    \RequirePackage{microtype}
} {}
```

The comment in line 101 seems to be wrong.

On lines 108 to 113, we read:

```latex
% :)
\ifthenelse{\boolean{with-comicsans}}{
    % NOTE must be compiled with xelatex or luatex
    \usepackage{fontspec}
    \setmainfont{Comic Sans MS}
} {}
```

Perhaps the line 101 is a copy and paste of line 110 (which is correct, because of the loading of `fontspec` at line 111).

**Comment by Foggalong** [comment]
Thanks so much for catching this!

This misunderstanding stemmed from Computer Modern Bright not actually being installed on my computer. Under those conditions, `pdflatex` fails to compile with an error. However with both `xelatex` and `lualatex`, they just gave a warning and finished compiling with a substitute font which happened to _look_ like CM Bright but actually wasn't.
